# Capitulo 3 - Autovalores y autovectores

In [1]:
import numpy as np
import scipy.linalg
import matplotlib.pyplot as plt

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


Calculamos los autovalores y autovectores de la matriz
$$
A = \begin{pmatrix}
2 & 3 \\
2 & 1
\end{pmatrix}
$$

In [43]:
A = np.array([[2,3],[2,1]])
Id = np.eye(2)
print(Id)

[[1. 0.]
 [0. 1.]]


In [3]:
# Espacio de autovectores del autovalor lambda = -1
scipy.linalg.null_space(A+Id)

array([[-0.70710678],
       [ 0.70710678]])

In [4]:
# Espacio de autovectores del autovalor lambda = 4
scipy.linalg.null_space(A-4*Id)

array([[0.83205029],
       [0.5547002 ]])

In [5]:
# Autovalores y autovectores con el comando eig
np.linalg.eig(A)

EigResult(eigenvalues=array([ 4., -1.]), eigenvectors=array([[ 0.83205029, -0.70710678],
       [ 0.5547002 ,  0.70710678]]))

In [6]:
# Podemos usar también eigvals para los autovalores
np.linalg.eigvals(A)

array([ 4., -1.])

In [74]:
# Matrices de cambios de base para llevar A a la forma diagonal
C_BE = np.array([[1,3],[-1,2]])
print(C_BE)
print(C_BE)

[[ 1  3]
 [-1  2]]
<built-in method transpose of numpy.ndarray object at 0x7407d9bc3570>


In [80]:
C_EB = np.linalg.inv(C_BE)
B = C_EB @ A @ C_BE
print(B)
avec = np.linalg.eig(A)[1].T
avec[0]

[[-1.00000000e+00 -1.77635684e-15]
 [ 0.00000000e+00  4.00000000e+00]]


array([0.83205029, 0.5547002 ])

In [83]:
def aproximacionAVal(A,k):
    avec = np.linalg.eig(A)[1].T[0]
    v0 = np.random.rand(np.shape(A)[0],1)
    tol = 1e-6
    for i in range(0,k):
        v0 = A @ v0
        v0 = v0/np.linalg.norm(v0,2)
        dif = np.linalg.norm(v0-avec)
        veces = []
        veces.append(i)
        array =  []
        array= array.append(v0)
        if dif < tol:
            break
    return (v0,avec,array,veces)


In [85]:
b = aproximacionAVal(A,100)
#los avecs estan columnas, el avec principal es el 4
b

(array([[0.83205029],
        [0.5547002 ]]),
 array([0.83205029, 0.5547002 ]))

In [90]:
np.linalg.eig(A)

EigResult(eigenvalues=array([1.26135826, 0.80729364, 0.1313481 ]), eigenvectors=array([[-0.42513581, -0.86011793,  0.15147666],
       [-0.90216423,  0.50992966, -0.98080898],
       [-0.07320681,  0.01299583,  0.1227541 ]]))

In [99]:
#curva 
import pandas as pd

## Método de la potencia

Para 
$$
A = \begin{pmatrix}
0.9 & 0.15 & 0.25 \\
0.075 & 0.8 &  0.25 \\
0.025 & 0.05 & 0.5
\end{pmatrix}
$$
y $v = (1, 2, 3)$, calcular $A^k v$ para distintos valores de $k$.

In [86]:
A = np.array([[0.9, 0.15, 0.25], [0.075, 0.8, 5.25], [0.025, 0.05, 0.5]])
v = np.array([-1,20,15])

In [87]:
A @ v

array([ 5.85 , 94.675,  8.475])

In [88]:
A @ A @ v

array([ 21.585 , 120.6725,   9.1175])

In [89]:
def estado(A, v, k):
    for i in range(k):
        v = A @ v
        print(v)
    return(v)

In [35]:
estado(A, v, 50)

[ 5.85  94.675  8.475]
[ 21.585  120.6725   9.1175]
[ 39.80675 146.02375  11.132  ]
[ 60.5126375  178.24750625  13.86235625]
[ 84.66408875 219.91382313  17.35636938]
[113.52384569 273.40180438  21.79047806]
[148.62935129 341.63574175  27.40342539]
[191.86263377 428.32377806  34.49923357]
[245.5497455  538.1696962   43.46237153]
[312.58581826 677.12943841  54.77841421]
[396.59125575 852.73416171  69.06032448]
[ 502.10733555 1074.49837709   87.08165172]
[ 634.84177149 1354.43542337  109.8184281 ]
[ 801.97751487 1707.7082191   138.50202951]
[1012.56150363 2153.45054381  174.68586358]
[1277.99440073 2715.80333162  220.32949657]
[1612.64783455 3425.22210236  277.90477489]
[2034.64256017 4320.12633762  350.52968842]
[2566.8296769  5448.98012634  442.1372251 ]
[3238.02803443 6872.9167586   557.68836079]
[4084.58483498 8669.0494036   703.44071918]
[ 5152.34394181 10934.64716122   887.28745065]
[ 6499.12848448 13792.40264051  1119.18468193]
[ 8197.87220259 17397.07632887  1411.6906851 ]
[10340.

array([3431740.46901201, 7282363.50364818,  590932.95581585])

In [36]:
w = np.array([3.75, 1.875, 0.375])
A @ w

array([3.75 , 3.75 , 0.375])

In [37]:
ev = np.linalg.eigvals(A)
print(ev)

[1.26135826 0.80729364 0.1313481 ]


In [38]:
# Que pasa si cambiamos A por una matriz cualquiera?
A = np.random.rand(3,3)
print(estado(A, v, 50))

[16.7863392  23.17024595 21.22304729]
[19.76596387 39.70099934 44.33369097]
[34.51299042 66.15486119 74.5454738 ]
[ 57.56504395 111.51926216 126.23743745]
[ 97.08560786 187.8772602  212.73070383]
[163.56550716 316.60981617 358.53487107]
[275.64318589 533.54241505 604.19817455]
[ 464.50693341  899.1179465  1018.18911442]
[ 782.78060478 1515.18013722 1715.83748119]
[1319.13021804 2553.35940394 2891.50445425]
[2222.97896644 4302.88389646 4872.72101761]
[3746.13162121 7251.15699812 8211.43819588]
[ 6312.92620963 12219.54369953 13837.79552902]
[10638.45089989 20592.19629095 23319.25060294]
[17927.76183385 34701.66796004 39297.25999456]
[30211.60198918 58478.74321895 66223.16768979]
[ 50912.14972701  98547.52262645 111598.31345676]
[ 85796.40996043 166070.84354481 188063.84534083]
[144582.85500746 279860.15620328 316922.44110914]
[243648.91225345 471616.24134818 534073.06171235]
[410593.58275381 794760.79096385 900012.11100282]
[ 691926.29935995 1339319.25891238 1516687.24379143]
[1166024.07

In [39]:
# Modificamos el programa anterior, normalizando en norma-2 en cada paso
def estado_normalizado(A, v, k):
    for i in range(k):
        v = A @ v
        v = v / np.linalg.norm(v,2)
        print(v)
    return(v)

In [40]:
estado_normalizado(A, v, 50)

[0.4712106  0.65041373 0.59575377]
[0.31520459 0.63310533 0.70698211]
[0.32721983 0.62721839 0.70677031]
[0.32338805 0.62649125 0.70917479]
[0.32365855 0.62633467 0.70918969]
[0.32356384 0.62631474 0.70925051]
[0.32356987 0.62631059 0.70925142]
[0.32356752 0.62631005 0.70925297]
[0.32356765 0.62630994 0.70925301]
[0.32356759 0.62630993 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.62630992 0.70925305]
[0.32356759 0.626309

array([0.32356759, 0.62630992, 0.70925305])

Repetir para la matriz
$$
A = \begin{pmatrix}
3 & 1 & 2 \\
0 & 1 & -2 \\
1 & 2 & 4
\end{pmatrix}
$$ y $v = (1,2,3)$.

In [ ]:
A = -np.array([[3,1,2], [0,1,-2], [1,2,4]])
v = np.array([1,2,3])
v50 = estado_normalizado(A, v, 50)
print(v50)

In [ ]:
np.linalg.eigvals(A)

In [ ]:
np.linalg.norm(A@v50)

In [ ]:
# Autovalores de A
np.linalg.eigvals(A)

In [ ]:
# Si introducimos una pequeña modificacion en A, la matriz resulta diagonalizable
A = np.array([[1.0001,1,0],[0,0.999,1],[0,0,1]])
np.linalg.eig(A)

In [ ]:
# Matriz diaogonalizable
A = np.array([[-1,3,-1],[-3,5,-1],[-3,3,1]])
np.linalg.eig(A)

In [ ]:
# Usamos null space para calcular los autovectores
A = np.array([[0,1,0],[0,0,1],[0,0,0]])
scipy.linalg.null_space(A)

# Norma-2 de matrices

In [ ]:
# Graficamos 300 puntos al azar en la circunferencia de radio 1
plt.figure(figsize=(6,6))
for i in range(300):
    p = np.random.rand()*2*np.pi
    plt.scatter(np.cos(p), np.sin(p))

In [ ]:
# Norma-2 para matrices simétricas
A = np.array([[1,4], [4,-3]])

# Tomamos 300 puntos al azar en la circunferencia y graficamos las imágenes
plt.figure(figsize=(6,6))
plt.xlim((-6,6))
plt.ylim((-6,6))
for i in range(300):
    p = np.random.rand()*2*np.pi
    v = np.array([np.cos(p), np.sin(p)])
    Av = A @ v
    plt.scatter(Av[0], Av[1])
    

In [ ]:
# Agregamos los autovectores de A

# Norma-2 para matrices simétricas
A = np.array([[1,4], [4,-3]])

# Tomamos 300 puntos al azar en la circunferencia y graficamos las imágenes
plt.figure(figsize=(6,6))
plt.xlim((-6,6))
plt.ylim((-6,6))
for i in range(300):
    p = np.random.rand()*2*np.pi
    v = np.array([np.cos(p), np.sin(p)])
    Av = A @ v
    plt.scatter(Av[0], Av[1])

# Graficamos los autovectores de A
e = np.linalg.eig(A)
evec1 = e[1][0:2,0]*10
evec2 = e[1][0:2,1]*10

plt.arrow(0,0,evec1[0], evec1[1])
plt.arrow(0,0,evec2[0], evec2[1])

In [ ]:
# Norma-2 para matrices en general
A = np.array([[1,3], [-1,5]])

# Tomamos 300 puntos al azar en la circunferencia y graficamos las imágenes
plt.figure(figsize=(6,6))
plt.xlim((-6,6))
plt.ylim((-6,6))
for i in range(300):
    p = np.random.rand()*2*np.pi
    v = np.array([np.cos(p), np.sin(p)])
    Av = A @ v
    plt.scatter(Av[0], Av[1])
    
# Graficamos los autovectores de A
e = np.linalg.eig(A)
evec1 = e[1][0:2,0]*10
evec2 = e[1][0:2,1]*10

plt.arrow(0,0,evec1[0], evec1[1])
plt.arrow(0,0,evec2[0], evec2[1])    

In [ ]:
# Agregamos las imágenes de los autovectores de A.T @ A

# Norma-2
A = np.array([[1,3], [-1,5]])

# Tomamos 300 puntos al azar en la circunferencia y graficamos las imágenes
plt.figure(figsize=(6,6))
plt.xlim((-6,6))
plt.ylim((-6,6))
for i in range(300):
    p = np.random.rand()*2*np.pi
    v = np.array([np.cos(p), np.sin(p)])
    Av = A @ v
    plt.scatter(Av[0], Av[1])

# Graficamos las imágenes de los autovectores de A.T @ A
e = np.linalg.eig(A.T@A)
evec1 = A@e[1][0:2,0]*10
evec2 = A@e[1][0:2,1]*10

plt.arrow(0,0,evec1[0], evec1[1])
plt.arrow(0,0,evec2[0], evec2[1])
